<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Combine the JSON files generated by the process_export task into single yearly files for summative and formative.
 *
 * @package    report_feedback_tracker
 * @copyright  2025 onwards Catalyst IT {@link http://www.catalyst-eu.net/}
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 * @author     Conn Warwicker <conn.warwicker@catalyst-eu.net>
 */

namespace report_feedback_tracker\task;

use core\exception\moodle_exception;
use core\task\scheduled_task;
use FilesystemIterator;
use RegexIterator;
use report_feedback_tracker\local\helper;
use stdClass;

/**
 * Combine the JSON files generated by the process_export task into single yearly files for summative and formative.
 */
class amalgamate_files extends scheduled_task {
    /**
     * @var string The directory path to where the files are stored.
     */
    protected string $path;

    /**
     * Get the task name.
     *
     * @return string
     */
    public function get_name(): string {
        return get_string('task:amalgamate_files', 'report_feedback_tracker');
    }

    /**
     * Execute the task.
     * @return void
     */
    public function execute(): void {
        global $DB;

        // If there are any of the adhoc tasks still pending, we shouldn't run this yet, or we could end up with incomplete data.
        $adhoctasks = $DB->count_records('task_adhoc', [
            'component' => 'report_feedback_tracker',
            'classname' => '\\report_feedback_tracker\\task\\process_export',
        ]);

        // If there are still adhoc tasks processing the data and creating the individual files, we shouldn't try to
        // amalgamate them yet, or we could cause incorrect data to be written to the yearly file.
        if ($adhoctasks) {
            mtrace('There are still ' . $adhoctasks . ' process_export tasks pending, so we cannot run this task yet.');
            return;
        }

        // If the path is configured use it, otherwise use the temp directory.
        $this->path = get_config('report_feedback_tracker', 'export_path') ?: make_temp_directory('report_feedback_tracker');

        $academicyear = (int)get_config('report_feedback_tracker', 'export_academicyear') ?: helper::get_current_academic_year();
        $previousyear = $academicyear - 1;
        $academicyears = [$previousyear, $academicyear];

        foreach ($academicyears as $acyear) {
            // Find all the files we have saved for this year.
            $files = [];
            $files['formative'] = $this->find_files($acyear, 'formative');
            $files['summative'] = $this->find_files($acyear, 'summative');

            // Make the yearly files.
            $formativefile = helper::make_and_open_file($this->path . "/feedback_tracker_report_{$acyear}_formative.json");
            $summativefile = helper::make_and_open_file($this->path . "/feedback_tracker_report_{$acyear}_summative.json");

            foreach ($files as $type => $itfiles) {
                $next = false;
                foreach ($itfiles as $fileinfo) {
                    $path = $fileinfo->getPathname();
                    $contents = file_get_contents($path);
                    if ($type === 'formative') {
                        $filehandle = $formativefile;
                    } else if ($type === 'summative') {
                        $filehandle = $summativefile;
                    }
                    // If this isn't the first record we're writing, add a comma and a newline.
                    helper::write_json_record($filehandle, ($next) ? ",\n" . $contents : $contents, 0);
                    $next = true;
                    mtrace('Written contents of ' . $path . ' to the ' . $type . ' file (' . $acyear . ')
                        - memory usage: ' . memory_get_usage() . ' bytes');
                }
            }

            // Close the files.
            helper::close_file($formativefile);
            helper::close_file($summativefile);
        }

        // Trigger an event.
        $event = \report_feedback_tracker\event\data_export_completed::create([
            'context' => \context_system::instance(),
        ]);
        $event->trigger();
    }

    /**
     * Find all the files for a given year and type.
     * @param int $year
     * @param string $type
     * @return RegexIterator Iterator containing the file paths
     */
    protected function find_files(int $year, string $type): RegexIterator {
        $iterator = new FilesystemIterator($this->path, FilesystemIterator::SKIP_DOTS);
        return new RegexIterator(
            $iterator,
            '/feedback_tracker_report_' . $year . '_.+_' . $type . '\.json$/i',
            RegexIterator::MATCH
        );
    }
}
